DELETE http://localhost:3000/api/users/Alex HTTP/1.1

###

DELETE http://localhost:3000/api/users/lmachens

###

DELETE http://localhost:3000/api/users/anke9000

###

GET http://localhost:3000/api/users/lmachens HTTP/1.1

###

GET http://localhost:3000/api/users/ HTTP/1.1

###

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Steve",
    "username": "steven1",
    "password": "sicher"
}

### Login Leon

POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "lmachens",
    "password": "asdc"
}

### Login Anke

POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "anke9000",
    "password": "ab"
}

### Logout

POST http://localhost:3000/api/logout HTTP/1.1


### Get logged in user

GET http://localhost:3000/api/me HTTP/1.1